New Grpc web service initial
morganstanley/ComposeUI pull request #679
Opened 2024-06-03 10:19 UTC by agyen

2024-06-03 12:10 UTC, psmulovics commented
Can you please add the Grpc and protobuf version updates into this PR? #654 , #655 , #656 , #658

2024-06-14 17:00 UTC, bingenito commented on prototypes/process-explorer/dotnet/src/gRPC-Web-Service/DependencyInjection/ProcessExplorerBuilder.cs
> +namespace gRPC_Web_Service.DependencyInjection;
Should namespace have org and product prefix?

2024-07-22 09:55 UTC, ZKRobi requested changes

2024-07-22 09:55 UTC, ZKRobi commented on prototypes/process-explorer/dotnet/src/MorganStanley.ComposeUI.ProcessExplorer.Abstractions/Processes/ProcessInfoMonitor.cs
The abstractions project shouldn't contain implementation, please move implementations to the appropriate project

2024-07-22 09:55 UTC, ZKRobi commented on prototypes/process-explorer/dotnet/src/MorganStanley.ComposeUI.ProcessExplorer.Abstractions/Processes/ProcessInfoMonitor.cs
> +            //_logger.ProcessExpected(exception);
Is this intentionally commented? If yes, please replace with a comment explaining why the exception is swallowed

2024-07-22 09:55 UTC, ZKRobi commented on prototypes/process-explorer/dotnet/src/MorganStanley.ComposeUI.ProcessExplorer.GrpcWebServer/Extensions/ProtoConvertHelper.cs
> +        return new MorganStanley.ComposeUI.ProcessExplorer.Abstractions.Entities.ConnectionInfo(
Move the namespace to a using statement at the top instead

2024-07-22 09:55 UTC, ZKRobi commented on prototypes/process-explorer/dotnet/src/MorganStanley.ComposeUI.ProcessExplorer.GrpcWebServer/MorganStanley.ComposeUI.ProcessExplorer.GrpcWebServer.sln
This file shouldn't be necessary

2024-07-22 09:55 UTC, ZKRobi commented on prototypes/process-explorer/dotnet/src/MorganStanley.ComposeUI.ProcessExplorer.GrpcWebServer/Server/Abstractions/ProcessExplorerBuilderExtensions.cs
This abstractions folder contains a 3 non-abstraction classes, please consider rearranging into appropriate places

2024-07-22 09:55 UTC, ZKRobi commented on prototypes/process-explorer/dotnet/src/MorganStanley.ComposeUI.ProcessExplorer.GrpcWebServer/gRPC-Web-Service.sln
This solution shouldn't be necessary

2024-07-22 09:55 UTC, ZKRobi commented on prototypes/process-explorer/dotnet/test/MorganStanley.ComposeUI.ProcessExplorer.IntegrationTests/ServerEndToEndTests.cs
Why are all these e2e tests removed?

2024-07-22 09:55 UTC, ZKRobi commented on prototypes/multi-module-prototype/examples/multi-module-example/ComposeUI.Example.WPFDataGrid.TestApp/App.xaml.cs
This example doesn't compile because the src\messaging\dotnet\src\Abstractions\MorganStanley.ComposeUI.Messaging.Abstractions.csproj is missing from the references

2024-07-23 08:39 UTC, agyen commented on prototypes/process-explorer/dotnet/src/MorganStanley.ComposeUI.ProcessExplorer.GrpcWebServer/Server/Abstractions/ProcessExplorerBuilderExtensions.cs
So to clarify this, the " Abstractions " folder contains concrete implementations. We might consider renaming the folder for better clarity.

2024-07-23 08:40 UTC, agyen commented on prototypes/process-explorer/dotnet/test/MorganStanley.ComposeUI.ProcessExplorer.IntegrationTests/ServerEndToEndTests.cs
This was for the old process explorer which has been removed.

2024-08-01 09:15 UTC, ZKRobi commented on prototypes/process-explorer/dotnet/src/MorganStanley.ComposeUI.ProcessExplorer.Abstractions/Processes/ProcessInfoMonitor.cs
Please move this under the Core project

2024-08-02 14:00 UTC, ZKRobi approved these changes

2024-08-05 12:14 UTC, lilla28 approved these changes

2024-08-06 10:31 UTC, kruplm approved these changes

2024-08-06 11:59 UTC, merged