fdc3 e2e test
morganstanley/ComposeUI pull request #754
Opened 2024-08-27 09:20 UTC by agyen

Automated test for displaying pricing data and opening chart using sikuli

2024-08-27 14:19 UTC, ZKRobi commented
Could you add a readme explaining prerequisites and instructions on running the tests?

2024-08-29 14:39 UTC, ZKRobi requested changes

2024-08-29 14:39 UTC, ZKRobi commented on README.md
> +1. [Download](https://launchpad.net/sikuli/+download) sikuli IDE jar file.
I don't think this is the official link, can we look into this?

2024-08-29 14:39 UTC, ZKRobi commented on README.md
> +2. [Download](https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar) jython standalone jar file.
As far as I can tell this is not necessary for the latest version

2024-08-29 14:39 UTC, ZKRobi commented on README.md
> +4. Click on run(Make sure FDC3-Chart-and-Grid is running in the background and the next application after the IDE)
Based on the attached screenshots the "Shell" launch configuration needs to be started (but yes, the hosting is necessary).
Please clarify this a bit as there is a Chart and Grid launch configuration as well that looks different and wouldn't work.

2024-08-29 14:42 UTC, ZKRobi commented on examples/fdc3-chart-and-grid/fdc3-chart-and-grid.sikuli/grid-and-chat-display-automated-test.py
> +    popup("Module not found, can't continue")
Please clarify this message to reflect that it's looking for the folder :)

2024-08-29 14:48 UTC, ZKRobi commented on README.md
> +1. [Download](https://launchpad.net/sikuli/+download) sikuli IDE jar file.
Ok now I can see launchpad is official as well, strange project

2024-08-29 15:00 UTC, ZKRobi commented on examples/fdc3-chart-and-grid/fdc3-chart-and-grid.sikuli/grid-and-chat-display-automated-test.py
> +if exists("./screenshots/modules"):
Quite unfortunately this is relative to the working directory, and not the script. We can live with this, or solve it later, but it's worth noting in the readme

2024-09-03 07:40 UTC, ZKRobi submitted a review, later dismissed

2024-09-04 13:23 UTC, lilla28 submitted a review, later dismissed

2024-09-10 11:52 UTC, ZKRobi approved these changes

2024-09-11 13:23 UTC, merged