Adaptive cards/notifications
morganstanley/ComposeUI pull request #834
Opened 2024-11-15 22:01 UTC by Sanjuice

This is pull request to expand on the adaptive cards poc with notifications for success, error and information.

2024-11-18 15:52 UTC, ZKRobi commented
This is a good start however we need the notifications to appear outside of the web module. Could you extend the PR with this?

2024-11-19 08:35 UTC, speed-y requested changes

2024-11-19 08:35 UTC, speed-y commented on examples/adaptive-cards/app.js
> +const renderNotif = (notifType, bgColor ) => {
I would prefer to rename the variables to complete names - `renderNotification`, `notificationType`

2024-11-19 08:35 UTC, speed-y commented on examples/adaptive-cards/app.js
> +    let notifCard = new AdaptiveCards.AdaptiveCard();
`notifCard` -> `notificationCard`

2024-11-21 00:50 UTC, Sanjuice commented
> This is a good start however we need the notifications to appear outside of the web module. Could you extend the PR with this?

Thanks :) Regarding the notifications appearing using ComposeUI, it would be done in a task by a member from the .NET team so the use case of making the notifications appear outside of the web module would be dealt in that PR. This PR is more regarding the styling of the cards to see how the cards can be styled for different types of notifications.

2024-12-03 10:56 UTC, kruplm requested changes

2024-12-03 10:56 UTC, kruplm commented on examples/adaptive-cards/index.html
> +        <script type="text/javascript" src="https://unpkg.com/markdown-it/dist/markdown-it.min.js"></script>
CDNs can time out and be blocked on the firewall.
Could you change the consumption of markdown-it to be through an installed NPM package?

2024-12-09 16:35 UTC, kruplm approved these changes

2024-12-10 15:29 UTC, lilla28 approved these changes
Please do not forget squashing your commits!

2024-12-16 04:43 UTC, merged