AC notification library
morganstanley/ComposeUI pull request #869
Opened 2024-12-24 07:00 UTC by Sanjuice

This is a pull request to create a library for Toast notifications that can be created by a client side application.

2025-01-14 09:57 UTC, kruplm requested changes

2025-01-14 09:57 UTC, kruplm commented on examples/adaptive-cards/showcase/index.html
>      <body>
I like the demo with the default behavior where the notifications disappear after a certain time, but could you add two buttons so that the notifications can triggered with a click event?

2025-01-19 20:10 UTC, Sanjuice commented on examples/adaptive-cards/showcase/index.html
>      <body>
The buttons have been added to the main application and can trigger the notifications from there.

2025-01-22 09:20 UTC, kruplm commented
LGTM, but it seems there's a conflict now in the `package.json` and `package-lock.json` files. @Sanjuice could you resolve those?

2025-01-22 23:45 UTC, Sanjuice commented
The merge conflicts are caused because of moving the packages around within the same folder. I tried to resolve them by merge the target branch but nothing really changes. They will have to be resolved when merging the pr.

2025-01-23 13:27 UTC, kruplm approved these changes

2025-01-23 16:33 UTC, lilla28 reviewed
Running lerna run build and test on the monorepo:
Failing build :
 1/14 targets failed, including the following:

      - @morgan-stanley/composeui-example-chart-messagerouter:build
       Error: Cannot find module 'interpret'
       
     Test is failing for:
      @morgan-stanley/composeui-node-launcher:test:
      executeScriptFile.spec.ts:8:25 - error TS2454: Variable 'testFileName' is used before being assigned.

2025-01-23 16:33 UTC, lilla28 commented on examples/adaptive-cards/library/README.md
> +1. Run npm install in the compose-ui folder.
nitpick: ComposeUI root folder

2025-01-23 16:33 UTC, lilla28 commented on examples/adaptive-cards/library/rollup.config.js
> +//import resolve from '@rollup/plugin-node-resolve';
please remove commented out code

2025-01-23 16:33 UTC, lilla28 commented on examples/adaptive-cards/library/src/customElement.ts
> +  //#region Schema
nitpick: I would avoid using regions sections

2025-01-23 16:33 UTC, lilla28 commented on examples/adaptive-cards/library/src/img/img.d.ts
> +// Morgan Stanley makes this available to you under the Apache License, Version 2.0 (the "License"). You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0. See the NOTICE
can you please help me out here what is this file? what its purpose? cause a little bit it looks lie as it's a generated file

2025-01-23 16:33 UTC, lilla28 commented on examples/adaptive-cards/library/src/notification.ts
> +interface notification {
nitpick I would rather create individual files for each class / interface definitions

2025-01-23 16:33 UTC, lilla28 commented on examples/adaptive-cards/library/src/img/sucess.png
nitpick: typo

2025-01-23 16:33 UTC, lilla28 commented on examples/adaptive-cards/library/src/customElement.ts
> +  private _templateElement?: HTMLElement;
nitpick: field name: templateElement without `_`

2025-01-23 17:20 UTC, kruplm commented
> interpret



> Running lerna run build and test on the monorepo: Failing build : 1/14 targets failed, including the following:
> 
> ```
>   - @morgan-stanley/composeui-example-chart-messagerouter:build
>    Error: Cannot find module 'interpret'
>    
>  Test is failing for:
>   @morgan-stanley/composeui-node-launcher:test:
>   executeScriptFile.spec.ts:8:25 - error TS2454: Variable 'testFileName' is used before being assigned.
> ```

The interpret library is a transitive dependency from webpack. After this PR is merged I'm going to sync the [prototypes/adaptive-cards](https://github.com/morganstanley/ComposeUI/tree/prototypes/adaptive-cards) branch with the main branch. That should resolve this issue.

2025-01-24 15:56 UTC, Sanjuice commented on examples/adaptive-cards/library/src/img/img.d.ts
> +// Morgan Stanley makes this available to you under the Apache License, Version 2.0 (the "License"). You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0. See the NOTICE
This file is to define the type for the images to typescript so that they can be embedded within the code. It's not a generated file. Does that help?

2025-01-24 17:08 UTC, merged